### ISSUE TITLE
Ordering of resource creation fails with k8 cluster

### ISSUE THREAD

**Issue by VarunkumarManohar** [GoogleCloudPlatform/deploymentmanager-samples#110]
I am trying to use the api exposed by a k8 cluster in other resources.

I want the k8 cluster to be up first and later other resources make use of  the api exposed by this k8 cluster.
I tried to  use the references to lay out an implicit order on the resource creation, but I see that even before the k8 cluster is fully up, another resource is trying to access an api exposed by the k8 cluster.

More details:
https://gist.github.com/VarunkumarManohar/508454c42afa481771e2c600120ca7ac

Unsure of why this is happening ..

**Comment by likeulb** [comment]
Hi @VarunkumarManohar,
I didn't see fullCluster property (specified in k8.yaml) has been used in nodeport.py. If this the case, the $(ref.dmcluster.selfLink) will not be used in the expanded config. You may go to Google Cloud Console, under the Deployment Manager, you can view the expanded config to see if the resources have the correct dependency. 
BTW, you also tried to specify the order with "dependsOn" in k8.yaml, this currently doesn't work with template.

**Comment by VarunkumarManohar** [comment]
@likeulb  even if I use the let's say context.properties['fullCluster'] inside nodeport.py, I see that the deployment manager is attempting to create the dmnginxservice before creating the dmcluster resource.

**Comment by VarunkumarManohar** [comment]
@likeulb  I have received another update from @krwenholz  that there is a wait issue with Google K8 cluster so I believe this is something already known- only thing is it would be helpful if the gke documentation inside Googel deployment manager samples mentions the prerequisite that all other k8 resources could be created only if the k8 is full up and hence such a deployment using K8 APIs needs to be done in a separate deployment and not in the same deployment as that of the cluster or put it other way references on cluster do not work ...

**Comment by likeulb** [comment]
Hi @VarunkumarManohar, I think in this particular case, there should be something wrong with your template that the ordering is not identified. Do you have most update to date template? In your current template, you tried to reference $(ref.dmcluster.selfLink), but dmcluster is a template (cluster.py), and I didn't see any output of this template named "dmcluster". Please try to specify an output in cluster.py. The value of the output should have the reference to the type provide name, maybe like '$(ref.' + type_name+type_suffix + '.name)', then reference the output in the k8.yaml file. If it istill doesn't work, please send me the most up to date template. Thanks.

**Comment by likeulb** [comment]
Hi @VarunkumarManohar any update regarding the issue?
