### ISSUE TITLE
project creation - "Find the Cloud Services service account" Missleading

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/deploymentmanager-samples#111]
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/project_creation

Prerequisites > Step 2 says:
"Find the Cloud Services service account associated with the DM Creation Project. It will be in the form <project_number>@cloudservices.gserviceaccount.com. This will be called the "DM Service Account" for the rest of these instructions."

The instruction should say where and how to find it:
https://cloud.google.com/iam/docs/service-accounts
"PROJECT_NUMBER@cloudservices.gserviceaccount.com

This service account is designed specifically to run internal Google processes on your behalf and is **not listed** in the Service Accounts section of GCP Console. "

**Comment by vagababov** [comment]
This is fixed in a pr.
