### ISSUE TITLE
Usage of base64Decode and KMS-based decryption of secrets

### ISSUE THREAD

**Issue by schweikert** [GoogleCloudPlatform/deploymentmanager-samples#127]
I am exploring the usage of gcp-types/cloudkms-v1:cloudkms.projects.locations.keyRings.cryptoKeys.decrypt" to automatically decrypt secrets at deploy time, as can be seen in this code snippet: [kms.jinja](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/google/resource-snippets/cloudkms-v1/kms.jinja).

Something that doesn't seem to work right is the use of the base64Decode() method in a $(ref). I get:

     The resource 'test-decrypt' exists, but the reference value does not, details: Unrecognized function base64Decode

@shuainie-google : maybe you could help?

**Comment by schweikert** [comment]
OK, I found out that base64Decode() only works when you put configVersion: v1alpha in your deployment config. Cool! I hope this functionality is moved out of alpha soon.

**Comment by abrahammartin** [comment]
Any idea how you specify the configVersion parameter if you are using python instead of jinja?

**Comment by schweikert** [comment]
No, sorry

**Comment by dinvlad** [comment]
@abrahammartin seems like `configVersion` is specified in configuration, not in the template. So it applies equally to jinja and python templates.
