### ISSUE TITLE
Updating GKE Cluster returns Error

### ISSUE THREAD

**Issue by der-schuessel** [GoogleCloudPlatform/deploymentmanager-samples#13]
Creating a deployment with deploymentmanager-samples/examples/v2/gke/python/ works perfectly whereas updating the deployment (eg increasing number of nodes) will return an error:

````
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1490030492265-54b2cc2322a2a-e276ea11-d8776693]: errors:
- code: CONDITION_NOT_MET
  location: /deployments/cluster4/resources/cluster4-test-cluster-1->$.properties
  message: '"": domain: validation; keyword: properties; message: required property(ies)
    not found; missing: ["clusterId"]; required: ["clusterId","zone"]'
````
Is this not supported or a mistake on my side?

**Comment by munutzer** [comment]
Deployment Manager does not support updates of the cluster resource yet. We are currently working on adding cluster update support.

**Comment by der-schuessel** [comment]
Thanks for the info!

**Comment by NathanHowell** [comment]
@munutzer do you have any idea when cluster update support will be added?
