### ISSUE TITLE
Struggling to replace the default `kube-dns` configmap using the Kubernetes type provider

### ISSUE THREAD

**Issue by nfirvine** [GoogleCloudPlatform/deploymentmanager-samples#136]
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/examples/v2/gke/jinja/cluster.jinja#L34

The DaemonSet example presumably gets deployed into the `default` namespace.

I suspect we need a new `inputMapping` for `namespace`, but the format is tough to follow and underdocumented.

**Comment by munutzer** [comment]
Namespace is an API property for Kubernetes resources so you should be able to set it like this https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/9524c3fcb5351f0ff05a6af430bf791fe1ae39f1/examples/v2/gke/jinja/replicatedservice.jinja#L31

Are you getting a Deployment Manager or Kubernetes error when specifying a namespace property?

**Comment by nfirvine** [comment]
I see. So `namespace` is a key in `properties`, rather than `metadata`. So how does it get added to `metadata`, if not by an additional `inputMapping`? My reading of the spec says it need to be in the URI and the `metadata`.

**Comment by nfirvine** [comment]
Also, Is the `isNull` function documented anywhere?

**Comment by nfirvine** [comment]
Ok, I think I've narrowed down my problem. The namespace thing is a red herring. I'll update the title.

I'm trying to use GDM to create the `kube-dns` configmap like https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/. It seems to work fine if I'm creating a new configmap, but on GKE at least, `cm/kube-dns` gets created automatically by the cluster itself.

I suspect that when doing a GDM `create`, it uses `createNamespacedConfigMap`. In my tests, calling that and trying to create a resource that exists yields a `409 Conflict`. GDM doesn't seem to surface this error.

I guess I would want to use `replaceNamespacedConfigMap`, since I expect it to exist. I tried specifying that path `type: '...:/api/v1/namespaces/{namespace}/configmaps/{name}` but I get this error:

```
- code: COLLECTION_NOT_FOUND
  message: Collection '/api/v1/namespaces/{namespace}/configmaps/{name}' not found
    in discovery doc 'https://redacted/swaggerapi/api/v1'
```

Which is definitely false; maybe it means that it wants a POST method for that collection.

Otherwise, creating configmaps works, even namespaced (though, like I mentioned, the syntax is definitely weird).

I can work around this problem, but it's not pretty:

1. `gdm create`
2. Make some trivial change to the configmap definition
3. `gdm update`

I wonder if there's a way to modify the API type to always prefer the PUT-style endpoint?

**Comment by shuainie-google** [comment]
Hi @nfirvine, the type you should be using in DM config for configmaps should be {projectName}/{clusterType}:/api/v1/namespaces/{namespace}/configmaps. However DM doesn't support all Kubernetes resource out of the box. We currently only support scenarios we have in the samples.
