### ISSUE TITLE
quick_start README typo

### ISSUE THREAD

**Issue by ocsi01** [GoogleCloudPlatform/deploymentmanager-samples#14]
In the **examples/v2/quick_start/README.MD** file the cli command has a typo:
`gcloud deployment-manager deployments create quick-start-deployment
--config/vm.yaml`

It should be:
`gcloud deployment-manager deployments create quick-start-deployment
--config vm.yaml`

**Comment by krwenholz** [comment]
Thanks for pointing out and fixing this Adam.
