### ISSUE TITLE
GKE type provider sometimes failing

### ISSUE THREAD

**Issue by schweikert** [GoogleCloudPlatform/deploymentmanager-samples#148]
Hi,

I am struggling a bit lately with my deployment based on the following code:
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/gke

The problem is that deployment manager sometimes reports:

    Waiting for create [operation-1523455329129-5699315b95229-abb36a8f-75ba2e65]...failed.
    ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1523455329129-5699315b95229-abb36a8f-75ba2e65]: errors:
    - code: DESCRIPTOR_URL_FETCH_ERROR
      location: /typeProviders/prod-cluster-type->$.descriptorUrl
      message: "{\"originalResponse\":\"{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\"\
        :\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\"\
        :\\\"Unauthorized\\\",\\\"reason\\\":\\\"Unauthorized\\\",\\\"code\\\":401}\"\
        ,\"reason\":\"The descriptor url 'https://192.0.2.10/swaggerapi/api/v1' for\
        \ type provider 'prod-cluster-type' could not be fetched.\"}"

(note: IP address is obfuscated)

 Note that the type is actually deployed using another deployment, so it isn't an issue of dependency resolution. Also, what is weird, is that if I re-run the deployment a few times, it suddenly works. Maybe a timeout issue? That swaggerapi endpoint is quite big...

**Comment by vagababov** [comment]
Our first guess that it's actually GKE issue and DM will not retry the request on 401 response.
I've asked GKE team to take a look.

**Comment by abeagley** [comment]
+1 here. Same scenario for the "workaround" as well. After a few retries things were setup normally.

**Comment by alexnsfx** [comment]
+1. Issue reported here as well https://issuetracker.google.com/issues/78000405

**Comment by jiang-wei** [comment]
+1 here.

**Comment by adamharwayne** [comment]
We believe we found and fixed this bug in our backend system. Please let us know if you see this again. 

I'll leave this issue open for the time being until we hear back that it is now working.

**Comment by schweikert** [comment]
It works well for me now. I am not seeing these errors anymore. Thanks a lot!
