### ISSUE TITLE
HostPort and container ports for Google Container VM  Docker image do not work

### ISSUE THREAD

**Issue by VarunkumarManohar** [GoogleCloudPlatform/deploymentmanager-samples#149]
I was able to start a container vm `cos-stable-65-10323-69-0.` using Google Deployment Manager.

When I specify the docker image to be started in the `gce-container-declaration` metadata key for resource type `compute.v1.instanceTemplate`, the docker container starts correctly when the  compute engine vm instance boots but the host and container ports passed as parameters are not being used
in running the docker image.

```
manifest = {
        'apiVersion': 'v1',
        'kind': 'Pod',
        'metadata': {
            'name': context.env['name']
        },
        'spec': {
            'containers': [{
                'name': context.env['name'],
                'image': context.properties['dockerImage'],
                'ports': [{
                    'hostPort': context.properties['hostPort'],
                    'containerPort': context.properties['containerPort']
                }],
            }]
        }
    }
```

HostPort and containerports are not being used while running the docker image as a result the docker container ends up running on 8080 port and not the hostport passed as a parameter

Is this a known issue or is some setting being missed out ?

**Comment by VarunkumarManohar** [comment]
I have created a [gist ]([url](https://gist.github.com/VarunkumarManohar/211bce1179e47d35bc2007c0cd7a6993)) for your reference.

Both host and container ports values are the same but still the docker container ends up running on 8080 and not the specified host ports for the deploy.py

**Comment by vagababov** [comment]
Thanks.
Could please check in cloud console the configuration for the instance_template and see if it has port 8080 or port 8083? We see that we sent 8083 in the request.

**Comment by VarunkumarManohar** [comment]
These are values inside the instance_template rest reference

1) with hostnetwork set to true
"value": "apiVersion: v1\nkind: Pod\nmetadata:\n  name: vmanohar-websocket-vm\nspec:\n  containers:\n  - image: gcr.io/google-containers/nginx\n    name: vmanohar-websocket-vm\n    ****ports:\n    - containerPort: 8083\n      hostPort: 8083\n**  hostNetwork: 'true'\n"**


2) without hostnetwork tag
"value": "apiVersion: v1\nkind: Pod\nmetadata:\n  name: vmanohar-websocket-vm\nspec:\n  containers:\n  - image: gcr.io/google-containers/nginx\n    name: vmanohar-websocket-vm\n    **ports:\n    - containerPort: 8083\n      hostPort: 8083\n**"


In both the cases the docker container still ends up running in a default port and not 8083

**Comment by vagababov** [comment]
It seems that the problem is inside GCE, rather than DM. We will keep you posted.

**Comment by VarunkumarManohar** [comment]
sure thanks.

**Comment by VarunkumarManohar** [comment]
hi @vagababov  just wanted to check with you if you have any updates ..

**Comment by vagababov** [comment]
hi no updates, we've pinged the team again.

**Comment by adamharwayne** [comment]
We've talked with the team and they said "hostPort support is not yet implemented".
