### ISSUE TITLE
Cloud Functions triggers

### ISSUE THREAD

**Issue by Spartanflyer** [GoogleCloudPlatform/deploymentmanager-samples#154]
The example has a default http trigger, I'm struggling to set a Pub/Sub topic trigger. I add to the schema:

eventTrigger:
    type: array
    items:
      type: object
      required:
      - eventType
      properties:
        eventType:
            type: string
        resource:
            type: string
        service:
            type: string

And add to the .yaml

eventTrigger:
      - eventType: topic
        resource: [TOPIC_NAME]
        service: google.pubsub.topic.publish

But the function created remains with an HTTP trigger. Could you please point me what am I missing.

**Comment by likeulb** [comment]
Hi @Spartanflyer ,
As I haven't heard from you, I'll close the issue for now. Feel free to reopen it if the problem still exists.
