### ISSUE TITLE
Samples Cloudfunction Deployment error

### ISSUE THREAD

**Issue by stanzheng** [GoogleCloudPlatform/deploymentmanager-samples#163]
Problem:
Following the readme and instructions of 
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/cloud_functions produces an error where reference to non-existant config file

environment: Google Cloud Shell functions 
PROJECT_ID set to project 

steps to reproduce 

1.  git clone repo
2. navigate to examples/v2/cloud_functions
3. gcloud deployment-manager deployments create my-function2 --config cloud_function.yaml --project $P
ROJECT_ID 

```
$ gcloud deployment-manager deployments create my-function2 --config cloud_function.yaml --project $P
ROJECT_ID
The fingerprint of the deployment is v-Nov_ObEimwrN-X9zYNQQ==
Waiting for create [operation-1526768191644-56c966bb7a162-d039b89c-8268fc97]...failed.
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1526768191644-56c966bb7a162-d039b89c-8268fc97]: errors:
- code: MANIFEST_EXPANSION_USER_ERROR
  location: /deployments/my-function2/manifests/manifest-1526768191913
  message: |
    Manifest expansion encountered the following errors: Error compiling Python code: No module named zipfile Resource: cloud_function.py Resource: config
```

**Comment by aljim** [comment]
Thanks for reporting this, is fixed now
