### ISSUE TITLE
Document how to configure configVersion on jinja2 or py templates

### ISSUE THREAD

**Issue by abrahammartin** [GoogleCloudPlatform/deploymentmanager-samples#169]
base64Decode requires usage of v1alpha of Google Deployment Manager (see #127). This is not documented anywhere (or at least I haven't found it after a lot of search) and it is apparently essential if you want to use secrets with Deployment Manager (as they are retrieved in base64 from Google KMS).

Where is configVersion specified if you are using a template? I have tried inside .jinja and inside .schema both unsuccessful.

**Comment by vagababov** [comment]
It can only be done via yaml files currently.
An examples would be: https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/706f2b62f7c7f5dcb920d5c7f50a4d53b0e2ef6b/google/resource-snippets/cloudkms-v1

**Comment by abrahammartin** [comment]
How do you propose to deploy secrets (that requires base64Decode) if you need to use a template (need to pass environment variables)?

**Comment by raelga** [comment]
Having the `configVersion` set to `v1alpha` in a random file in a GithHub repo does not solves the documentation problem.
