### ISSUE TITLE
update README for creating projects through deployment manager

### ISSUE THREAD

**Issue by grapesfrog** [GoogleCloudPlatform/deploymentmanager-samples#18]
Step 3:Create the project. If using the CLI:

gcloud deployment-manager deployments create --config config.yaml

should be 
gcloud deployment-manager deployments create  NAME_OF_YOUR_DEPLOYMENT  --config config.yaml

**Comment by krwenholz** [comment]
Thanks for pointing this out @grapesfrog. I have submitted [a fix](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/commit/34588c8d90cca85ab7dbd4495c371803d79fe3f5). Let us know if there's anything else.
