### ISSUE TITLE
Manifest expansion errors

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#181]
Hi,
in recent days I've a manifest that return some errors on expansion. For examples:

```
- code: MANIFEST_EXPANSION_USER_ERROR
  location: /deployments/resources/manifests/manifest-1529498015415
  message: 'Manifest expansion encountered the following errors: Output of the manifest
    expansion is too large on expandedManifest'
```
```
- code: MANIFEST_EXPANSION_TOO_MUCH_CPU
  location: /deployments/resources/manifests/manifest-1529498248676
  message: Manifest expansion used too much CPU

```
Is an issue that I can avoid or I've to take some workaround (for example split in two deployments)?

**Comment by thackem** [comment]
Hi,
It seems like your template is too big or requires more compute than we allow for a single expansion. As the bounds are per-expansion I believe splitting this in to two deployments would avoid the issue for you.
Were you able to deploy the same templates in the past without this issue?

**Comment by davidebelloni** [comment]
Hi,
I was able to deploy the _same_ deployment in the past, but it was made up of fewer resources.
It's a deployment that manage the dataset and tables of our BigQuery and use composite types, so it could become quite big.
Splitting it resolve the issue (obviously)

Thanks
