### ISSUE TITLE
Nit: better promote router sample with README since checkin comment is unrelated.

### ISSUE THREAD

**Issue by miketruty** [GoogleCloudPlatform/deploymentmanager-samples#19]
Super minor: consider adding a README for this cloud router sample since the check-in comment references other unrelated code.

![image](https://user-images.githubusercontent.com/2963569/28492003-36120392-6ec0-11e7-9cfe-e2761ee95b63.png)

**Comment by krwenholz** [comment]
Thanks for pointing this out Mike. I've added a [barebones README](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/commit/52c889bc92bb93681c83f997a52ddeacea484c88) until we come through and clean this up.
