### ISSUE TITLE
template schema importing all the files in a folder

### ISSUE THREAD

**Issue by varungbt** [GoogleCloudPlatform/deploymentmanager-samples#212]
This a section in a schema file

```
   imports:
    - path: configs/folder1/resources/gcpresource/test/*
```
I am trying to import all the files in a folder using the template's schema file. I know that this does not work.

My question is, what is a better way to import all the files using * or something that's suitable so that deployment manager can import all of the files in a folder without having to explicitly specify them ?

**Comment by ocsig** [comment]
This is a frequently requested feature which the Deployment Manager team is currently working on. Hold on just a little bit more.

**Comment by varungbt** [comment]
thanks @ocsig

**Comment by ocsig** [comment]
The feature is available for public use:
https://cloud.google.com/sdk/docs/release-notes#cloud_deployment_manager

> Added config key which enables globbing in the gcloud deployment-manager deployments <create|update> command. Config files can now use glob patterns in import paths.
This feature can be enabled by setting the config property deployment_manager/glob_imports to true: gcloud config set deployment_manager/glob_imports True.
Imports with a path pattern that match multiple files cannot be named.
When referencing a template in a resource type field, its full name is still required.
More information on globbing is available at [http://man7.org/linux/man-pages/man7/glob.7.html](http://man7.org/linux/man-pages/man7/glob.7.html).
More information on deployment-manager configurations is available at [https://cloud.google.com/deployment-manager/docs/configuration](https://cloud.google.com/deployment-manager/docs/configuration)/.

**Comment by varungbt** [comment]
@ocsig  Thanks. We already have started using this feature extensively.  
Based your conversation with Vincent, we took some leads and incorporated in our deployments and have been able to successfully import all of the files in folder without hassles. Indeed this is a very useful feature.

**Comment by xalien10** [comment]
> The feature is available for public use:
> https://cloud.google.com/sdk/docs/release-notes#cloud_deployment_manager
> 
> > Added config key which enables globbing in the gcloud deployment-manager deployments <create|update> command. Config files can now use glob patterns in import paths.
> > This feature can be enabled by setting the config property deployment_manager/glob_imports to true: gcloud config set deployment_manager/glob_imports True.
> > Imports with a path pattern that match multiple files cannot be named.
> > When referencing a template in a resource type field, its full name is still required.
> > More information on globbing is available at http://man7.org/linux/man-pages/man7/glob.7.html.
> > More information on deployment-manager configurations is available at https://cloud.google.com/deployment-manager/docs/configuration/.

@ocsig is is possible to import everything under a resource folder that may also include some sub folders with files?
