### ISSUE TITLE
Internal_lb example fails

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/deploymentmanager-samples#23]
cd deploymentmanager-samples/examples/v2/internal_lb/python
gcloud deployment-manager deployments create first-internal-lb  --config config.yaml

Issue1:
`- code: CONDITION_NOT_MET
  location: /deployments/first-internal-lb/resources/first-internal-lb-healthcheck->$.properties
  message: '"/type": domain: validation; keyword: enum; message: value not found in
    enum; enum: ["HTTP","HTTPS","INVALID","SSL","TCP"]; value: "tcp"'
`
At the internal_lb.py the healthcheck type should be capitaly  (TCP).

Issue2:

```
- code: RESOURCE_ERROR
  location: /deployments/first-internal-lb/resources/us-central1-first-internal-lb-allow-internal-traffic-firewall-rule
  message: '{"ResourceType":"compute.v1.firewall","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"errors":[{"domain":"global","message":"Invalid
    value for field ''resource.name'': ''us-central1-first-internal-lb-allow-internal-traffic-firewall-rule''.
    Must be a match of regex ''(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)''","reason":"invalid"}],"message":"Invalid
    value for field ''resource.name'': ''us-central1-first-internal-lb-allow-internal-traffic-firewall-rule''.
    Must be a match of regex ''(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)''","statusMessage":"Bad Request","requestPath":"https://www.googleapis.com/compute/v1/projects/xxx-privatetestproject/global/firewalls"}}'
```

The Firewall rule name is too long, the regexp only allows 62 character.
This means the stack name can be maximum 15 character long.

Issue3:

```
- code: RESOURCE_ERROR
  location: /deployments/first-i-lb/resources/us-central1-first-i-lb-allow-internal-traffic-firewall-rule
  message: '{"ResourceType":"compute.v1.firewall","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"errors":[{"domain":"global","message":"This
    feature is not yet supported.","reason":"badRequest"}],"message":"This feature
    is not yet supported.","statusMessage":"Bad Request","requestPath":"https://www.googleapis.com/compute/v1/projects/xxx-privatetestproject/global/firewalls"}}'
```

I have no clue for this error

**Comment by davidsac** [comment]
Thanks for pointing these issues out!  I will look into them.

**Comment by ocsig** [comment]
Issue3: I just had to update gcloud. The issue is resolved.
Issue 1 and 2 is still needs a fix.

**Comment by jaivasanth-google** [comment]
I just committed a fix to Issue 1.

**Comment by jaivasanth-google** [comment]
Resolving this issue. I am going to leave the naming of the firewall rull as is since it makes the templates more readable. Since these are sample templates, the user should feel free to modify the naming conventions to suite their needs.
