### ISSUE TITLE
Missing 'name' attribute in network.yaml example file

### ISSUE THREAD

**Issue by apsureda** [GoogleCloudPlatform/deploymentmanager-samples#237]
When running a deployment using the network.yaml example (cloud-foundation/templates/network/examples/network.yaml), I get this error:

```
- code: INVALID_CONFIG
  message: "Invalid config files: Template fetching failed: Failed to find imported\
    \ template 'network.py' for resource {name=test-network, properties={autoCreateSubnetworks=false,\
    ...
```
Which seems to me caused my the missing 'name' attribute in the import section of the yaml file:

```
imports:
  - path: templates/network/network.py

resources:
  ...
```
Adding name: network.py solves the issue.

**Comment by ocsig** [comment]
PR fixed the issue. tested.

**Comment by vinayan3** [comment]
Thanks for explaining this. I've been tearing my hair out over why my master template couldn't import another template and use it as a type. I added a name to it works.

**Comment by ocsig** [comment]
Just to be lear, if you import any file without a name tag, you can already use them with the full path. In the case above, this would work:
``type: templates/network/network.py
