### ISSUE TITLE
Project creation may need Compute Shared VPC Admin

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/deploymentmanager-samples#285]
If the project is a VPC host project, compute.organizations.enableXpnHost permission is needed, which can be added via roles/compute.xpnAdmin. (Compute Shared VPC Admin).
This should be in the readme as a pre-requirement.

**Comment by sourced-vince** [comment]
Hi Adam, I believe there is a comment under the `Prerequisites` section in the README.md.

`9. If the project is a VPC host project, give the DM Service Account the following permissions: roles/compute.xpnAdmin.

This update is in the `cloud-foundation` branch. Does this address the issue?

**Comment by ocsig** [comment]
Yes.
