### ISSUE TITLE
Cloud NAT sample

### ISSUE THREAD

**Issue by bbzg** [GoogleCloudPlatform/deploymentmanager-samples#294]
Hi,

Now that [Google Cloud NAT](https://cloud.google.com/nat/docs/) is a managed product (in Beta), it would be very powerful to configure it using Deployment Manager, but there is no [Resource Type](https://cloud.google.com/deployment-manager/docs/configuration/supported-resource-types) nor any [GCP Type Provider](https://cloud.google.com/deployment-manager/docs/configuration/supported-gcp-types) for it in the Deployment Manager documentation.

Essentialy, the managed Google Cloud NAT could be / is a replacement for the different [Terraform](https://github.com/GoogleCloudPlatform/terraform-google-nat-gateway) and [Deployment Manager](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/community/nat_gateway/README.md) templates out there.

When it moves out of Beta, I guess most documentation will be updated to reflect that the most convenient way to do NAT is using the managed NAT, but before that it would be really nice to provision Cloud NAT using Deployment Manager.

Any chance of a sample being created for how to do it?

Thanks!

**Comment by ocsig** [comment]
No samples yet, but you should be able to use type provider:
`gcp-types/compute-beta:compute.routers
`
[beta/routers](https://cloud.google.com/compute/docs/reference/rest/beta/routers)

**Comment by ocsig** [comment]
FYI: Cloud NAT is now [Generally Available](https://cloud.google.com/nat/docs/). Still no DM templates but we are looking into it.

**Comment by bbzg** [comment]
Still nothing?

**Comment by sourced-nan** [comment]
> Still nothing?
I just opened a PR for a NAT template I created a while ago.

https://github.com/GoogleCloudPlatform/deploymentmanager-samples/pull/429

**Comment by bbzg** [comment]
👏

**Comment by vital4ik** [comment]
I still dont see any templates for the cloud NAT. do you have an approximate ETA?

**Comment by ocsig** [comment]
Apologies for the slow reply, there is many thing going on in paralel.
There is an extended version of the Cloud Router template of the Cloud Foundation Toolkit in the new repo. It's currintly in the cft-dm-dev branch:
[https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev/dm/templates/cloud_router](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev/dm/templates/cloud_router)

This branch is almost ready to merge in to the master. These templates got a large refactoring including update to gcp-types, lates API version, extended schema files to support every parameter.

Alternatively take a look at this template writen by one of our partner:
[https://github.com/GoogleCloudPlatform/deploymentmanager-samples/pull/429](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/pull/429)

**Comment by ocsig** [comment]
FYI The CFT templates are moving the the new [repo](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit). The Cloud Foundation folder in this repo will be periodivally updated from there.
