### ISSUE TITLE
GKE Example Results in Non-functioning Kubernetes Cluster, When The Hosting Project is Built with DM

### ISSUE THREAD

**Issue by loffelmacher** [GoogleCloudPlatform/deploymentmanager-samples#31]
I ran through the instructions from the README here: https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/examples/v2/gke/README.md. After completing the two-step process outlined in the doc, I had a cluster with 4 nodes. However after the second step deploying the Kube Service & ReplicationController, I visit the "Workloads" tab in the GCP web UI, and I see "Unschedulable". 

**Update**: checked again and it appears that the problem is **only** happening when the project we try to add a cluster to was itself created through Deployment Manager. The example does actually work with a project created using the GUI. I did a quick comparison of enabled APIs and Service Accounts, they seem to be the same across both projects.

**Comment by colin92** [comment]
Found the problem was service account related. The DM projects did not have the compute engine auto-generated service account permissions added back to the project through the config file.

**Comment by loffelmacher** [comment]
Ok will close this for now.
