### ISSUE TITLE
Logsink destination is 'storage', not 'bucket'

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/deploymentmanager-samples#333]
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/9e38d8d75489c7660a0d6a424988d86809db66bf/community/cloud-foundation/templates/logsink/examples/project_logsink_bucket_destination.yaml#L34

"Bucket" is not an accepted destination. It has to be "storage"

**Comment by sourced-vince** [comment]
PR#336
[https://github.com/GoogleCloudPlatform/deploymentmanager-samples/pull/336](url)

**Comment by ocsig** [comment]
Fixed
