### ISSUE TITLE
Error in community/cloud-foundation/templates/dns_managed_zone/dns_managed_zone.py

### ISSUE THREAD

**Issue by Abdennebi** [GoogleCloudPlatform/deploymentmanager-samples#375]
When you create a DNS zone with the aforementioned template you will get this error:

````
The fingerprint of the deployment is XXX
Waiting for create [operation-XXX]...failed.
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-XXX]: errors:
- code: CONDITION_NOT_MET
  message: Referenced resource <ZONE NAME> could not be found.
    In 'finalValue' section of 'outputs' in the manifest layout.
````
IMHO the error is due to this [line](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/community/cloud-foundation/templates/dns_managed_zone/dns_managed_zone.py#L25):

````python
name_servers = '$(ref.' + context.properties['zoneName'] + '.nameServers)'
````

That should be:

````python
name_servers = '$(ref.' + context.env['name'] + '.nameServers)'
````
What do you think?

**Comment by ocsig** [comment]
Hi,

Can you clarify what properties are you passing to the template?
`zoneName` is an incoming parameter, which is marked as mandatory in the .schema file.
`context.env['name']` is referencing to the name of the deployment which can be fine, but seriously limiting the functionalities of a template.

**Comment by ocsig** [comment]
@Abdennebi can you please provide more infor on your issue?

**Comment by ocsig** [comment]
I managed to reproduce your issue, move it to high priority

**Comment by ocsig** [comment]
Issue fixed on the new repo. Changes will be merged here soon.
