### ISSUE TITLE
Manifest expansion used too much CPU

### ISSUE THREAD

**Issue by pivotalguru** [GoogleCloudPlatform/deploymentmanager-samples#398]
I have a listing in the GCP Marketplace that allows up to 129 nodes to be deployed.  When deploying the maximum size of 129 nodes, about 1/3 of the time the deployment will fail within a minute.  The error is "Manifest expansion used too much CPU".  From the command line, it is "MANIFEST_EXPANSION_TOO_MUCH_CPU".  

There is another issue that is similar to mine but the solution is to break up the Deployment into multiple, smaller ones to prevent this limit from being reached.  

Is this a feasible solution in the GCP Marketplace?  If so, how does a single Solution Create turn into multiple Deployments?  

Can this CPU limit be increased in Google to prevent this error?

Are there other workarounds to deployment this many nodes in a single Deployment?

**Comment by ocsig** [comment]
Hi,

The problem is not strictly the amount of resources but the time of the expansion ( the run of the python code). Is it possible that you can optimize your code a bit? I can take a quick look if you share the code with me.

Not knowing your architecture it's hard to say workarounds, but could you use instance groups instead of individually spinning up that many instances?

The rest of your questions is for the GCP Marketplace team. Do you have a channel to reach them?

**Comment by pivotalguru** [comment]
`
{% for index in range(instanceCount) %}
  - type: instance.jinja
    properties:
...
{% endfor %}
`
Do you have a good example for Instance Groups?  

I do have some contacts with the Marketplace team but we haven't figured out a good solution yet.

**Comment by ocsig** [comment]
Cloud Foundation Toolkit templates are covering Managed Instance Groups:
[https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/community/cloud-foundation/templates/managed_instance_group](community/cloud-foundation/templates/managed_instance_group)
A more minimalistic example:
[https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/instance_pool](examples/v2/instance_pool)

If you use a managed instance group, you create only a few resources (Instance template, Group manager) and then your deployment is done. From that point the Instance group scales up to your desired number but that is not limiting your Manifest expension time/size etc. 
Drawback if you need actions after the instances are ready is a bit trickier to implement.

**Comment by pivotalguru** [comment]
Thanks!  I'll dig into this and see what I can come up with.

**Comment by pivotalguru** [comment]
Is there a way to measure the CPU usage for a deployment expansion so I can see if my changes help?

**Comment by ocsig** [comment]
You can run the python code locally by calling the `generate_config(context)` function passing the inputs as a hasmap. I'm sure you can also run the Jinja template but that I don't have an experience.
If you run it locally, you can measure it. However I can tell, the instance group should be much faster then rendering the instance template 130 times. If you have no issues with instanceCount < 20, then it will solve the problem.
