### ISSUE TITLE
Cloud storage objects upload

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#40]
Can you provide an example about uploading an object to a Cloud Storage bucket?

Thanks

**Comment by krwenholz** [comment]
Hi Davide,

You could probably hack something into Deployment Manager using a feature we're working on (documentation coming sometime Q4), but uploading objects to Cloud Storage isn't really a supported use case. Your best tool for that is gcloud or the API.

What's your particular use case though? Is this file the same for every deployment? Are you referencing a GCS object in your deployment template?

**Comment by davidebelloni** [comment]
Hi,
I've a project that hosts golden images for others projects and (in a GCS bucket) their startup scripts.
I'm managing project and bucket with DM and images with Packer.
I can manage this GCS objects with gcloud or gsutil, but with something like DM the overall process should be more clear.

**Comment by aljim** [comment]
As a workaround you can define a cloud function that does that for you, here is a sample to call a cloud function within DM

https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/cloud_functions

**Comment by katyp** [comment]
Closing this issue. Please re-open if more is needed.

**Comment by krwenholz** [comment]
Hi Davide,

In the sample Alejandro linked to, you can see DM calling the raw Cloud Function. If the content you wanted was in your deployment, you could get it into Cloud Storage using their insert API in a similar way:

https://cloud.google.com/storage/docs/json_api/v1/objects/insert

You would need to do some configuring to get rid of that object on deletion of the deployment though (something we don't have docs for yet). Alternatively, you could copy objects between buckets with something like the following

    resources:
    - # All your existing resources.
    ...
    - name: some-name
      action: gcp-types/storage-v1:storage.objects.copy
      metadata:
        runtimePolicy:
        - CREATE
      properties:
        sourceBucket: my-source-bucket
        sourceObject: object-name
        destinationBucket: us-central1-bucket # Put the proper bucket name here.
        destinationObject: object-name

You would want to also add an action for deleting the object. It would look like the above but use a DELETE runtime policy and call the object delete API. Other acceptable policies are UPDATE_ALWAYS and UPDATE_ON_CHANGE (change of the deployment, not the object). 

Hopefully that helps and gets you going in the right direction. Let us know if there's anything else we can do to help.

Happy Monday.

**Comment by gadaldo** [comment]
Hi,

what about deleting a bucket with content in it (such as a previously created staging location)?

Regards

**Comment by krwenholz** [comment]
Hi @gadaldo,

There isn't an API to delete a bucket with content, so you would need to delete the contents first. This can be done via gcloud or the console. If you want to do the whole thing with Deployment Manager, I would recommend looking into running a a [Cloud Container Builder](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/cloudbuild) script in DM.

Hopefully that helps.

Happy Monday,

Kyle

**Comment by gadaldo** [comment]
Oh so there is not a way of say: 

```
- name: {{ PROJECT_NAME }}-event-dataflow
  type: storage.v1.bucket
  properties:
    location: europe-west2
    storageClass: REGIONAL
    deleteContents: True
```

cause I am trying but no luck.

Regards

**Comment by krwenholz** [comment]
Hi @gadaldo ,

Yes, this is a limitation of the [Google Cloud Storage API](https://cloud.google.com/storage/docs/json_api/v1/buckets/delete). Deployment Manager can only interact with APIs, so there is no declarative way for us to delete bucket contents, hence the suggestion to use a gcloud script like described in our Cloud Container Builder example (linked above).

Best,

Kyle

**Comment by alexanderposner** [comment]
In the years since this thread was started, has Google changed things? Is it possible to upload a file from Deployment Manager?
