### ISSUE TITLE
preview flag for deployments.insert() for a Java deployment manager client.

### ISSUE THREAD

**Issue by KishoreNamala** [GoogleCloudPlatform/deploymentmanager-samples#411]
How can we set the preview flag from a Java client on deployment configuration during an insert operation.

This is the signature of the API.
```Java
public Insert insert(java.lang.String project, com.google.api.services.deploymentmanager.model.Deployment content) 
```

My requirement is to preview the config before actually creating it.

More details on the question [here.](https://stackoverflow.com/questions/55290993/how-to-set-the-preview-flag-for-google-cloud-delpoyment-manager-deployments-inse)

**Comment by ocsig** [comment]
Duplicating the answer here for visibility:

The [DeploymentManager.deployments.instert class java doc ](https://developers.google.com/resources/api-libraries/documentation/deploymentmanager/v2/java/latest/) may help you with the possible actions.

My educated guess is you need to call this before execute():

`insReq.setPreview(true);`

**Comment by KishoreNamala** [comment]
:thumbsup:
Thank you @ocsig . 

I think I got carried by cancelPreview API and was expecting some similar name for this one too.
