### ISSUE TITLE
Add option to delete default VPC after project creation

### ISSUE THREAD

**Issue by claudiobizzotto** [GoogleCloudPlatform/deploymentmanager-samples#425]
It would be nice to have the option to delete the VPC (`default`) generated out of the box on project creation. (It looks like Terraform already has this [feature](https://github.com/terraform-providers/terraform-provider-google/issues/1312).)

This could be done right after the project gets created ([project_creation](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/project_creation)) or when a custom VPC gets created (as in the community's [network templates](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/community/cloud-foundation/templates/network)).

I already have the patches for option one, which I'll be submitting soon.

**Comment by Abdennebi** [comment]
I'am using this templates which already includes default VPC creation (https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/community/cloud-foundation/templates/project/project.py.schema#L148).

Also, since recently, it is possible to skip default network creation by defining a policy at the organization level.

**Comment by claudiobizzotto** [comment]
> I'am using this templates which already includes default VPC creation (https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/community/cloud-foundation/templates/project/project.py.schema#L148).
> 
> Also, since recently, it is possible to skip default network creation by defining a policy at the organization level.

I'm aware of the templates located under `cloud-foundation`, but this PR is not about fixing/improving those templates (as per my comment above).
