### ISSUE TITLE
Resources not updatable

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#44]
Hi,
some supported resources has fileds that cannot be update with a "gcloud deployment-manager deployments update" execution.

For example:
```
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1507190273341-55ac814d9f648-efa866de-deec4e38]: errors:
- code: NO_METHOD_TO_UPDATE_FIELD
  message: No method found to update field 'localTrafficSelector' on resource 'resources-tmp-tunnel'
    of type 'compute.v1.vpnTunnel'. The resource may need to be recreated with the
    new field.
```

VPNTunnel has, as well as firewall/routes/... , fields not updatable, in this case what is the best solution?
- Separate in different config deployment this resources from other, so that be able to delete and recreate them when necessary
- Change manually the resource on the web console e syncronize the code deployment "offline"
- Others?

Thanks

**Comment by katyp** [comment]
Hi there!

One option is to rename the resource before deployment. This will cause Deployment Manager to delete and then recreate it. Will that work for you?

**Comment by davidebelloni** [comment]
Hi,
the rename step is to do manually modifying Deployment Manager configuration or do you know a  way to do this automatically using DM? 
In the second case it's not the best solution, but maybe sufficient.
The first is somewhat a workaround like using "different config deployment"

**Comment by katyp** [comment]
That's correct; it's basically a workaround. We currently don't have any automated way to specify that a resource needs to be deleted and then re-created. I believe it's a popular feature request, though, so know that it's on our radar.

I'll close this issue for now, but please feel free to reopen it if necessary.
