### ISSUE TITLE
Python configuration: when is yaml.dump required?

### ISSUE THREAD

**Issue by bbzg** [GoogleCloudPlatform/deploymentmanager-samples#444]
Hi,

I have some templates that are written in Python, and they consistently do `yaml.dump(...` as the return value from `generate_config`, but when browsing the examples, it does not seem to be used very often.

Is it possible to clarify somewhere what is the idiomatic way to do this?

**Comment by ocsig** [comment]
Would you be able to link where do you see templates where they return with yaml.dump() from a generate_config?
Generally speaking returning the hashmap is appropriate:
` {
        'resources': [list_of_resources],
        'outputs': [list_of_outputs]
}
`

yaml.dump is appropriate to use when you want to return a string. ( For example in the middle of an instance startup script.)

**Comment by bes** [comment]
Typically I have done something like this:

```
import yaml

def GenerateConfig(context):

    resources = {
        'resources': [{
            'name': context.env['name'],
            'type': 'compute.v1.network',
            'properties': {
                'autoCreateSubnetworks': False,
                'description': 'The network resource for betterwse'
            }
        }]
    }

    return yaml.dump(resources)
```

But should probably not do yaml.dump anymore then.

Thanks for the clarification.

**Comment by bbzg** [comment]
```
import yaml

def GenerateConfig(context):

    resources = {
        'resources': [{
            'name': context.env['name'],
            'type': 'compute.v1.network',
            'properties': {
                'autoCreateSubnetworks': False,
                'description': 'The network resource'
            }
        }]
    }

    return yaml.dump(resources)
```

But should probably not do yaml.dump anymore then.

Thanks for the clarification.
