### ISSUE TITLE
CFT: GKE template output error (nodeIpv4CidrSize)

### ISSUE THREAD

**Issue by claudiobizzotto** [GoogleCloudPlatform/deploymentmanager-samples#446]
When creating a GKE cluster on a service project with access to a shared VPC, the deployment breaks with the following error:

```
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation 
[operation-xxxxxxxxxxxxx-xxxxxxxxxxxxx-xxxxxxxx-xxxxxxxx]: errors:
- code: REFERENCE_VALUE_NOT_FOUND
  location: /deployments/service/resources/xxxxx-cluster->$.properties
  message: |-
    The reference 'nodeIpv4CidrSize' is not found, reason:
    The resource 'xxxxx-cluster' exists, but the reference value does not.
```

I was able to create the cluster after removing `nodeIpv4CidrSize` from the outputs in [`gke.py`](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/3bceede418889be850924a7280aefa0d8414a41d/community/cloud-foundation/templates/gke/gke.py#L119).

I haven't seen the same error show up when deploying GKE clusters on a regular (non shared) VPC.

**Comment by bohdanyurov-gl** [comment]
Could you please provide example DM config?

**Comment by bohdanyurov-gl** [comment]
Nevermind, I've reproduced the issues. Fix is on the way
