### ISSUE TITLE
Error creating compute.v1.cluster

### ISSUE THREAD

**Issue by mbaroody** [GoogleCloudPlatform/deploymentmanager-samples#456]
I am trying to create a GKE cluster with Deployment Manager using the following as a reference: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters. I know this differs from the examples in this repository slightly. I used the documentation instead of the examples because the [examples](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/examples/v2/gke/python/cluster.py) use fields that are listed as deprecated. Here is my template: 

```python
def generate_config(context):
    CLUSTER_NAME = context.env["project"] + "-cluster"
    INITIAL_CLUSTER_VERSION = context.properties["initialClusterVersion"]
    INITIAL_NODE_COUNT = context.properties["initialNodeCount"]
    MACHINE_TYPE = context.properties["machineType"]
    ZONE = context.properties["zone"]
    SERVICE_ACCOUNT = context.properties["serviceAccount"]
    resources = [{
        "name": CLUSTER_NAME,
        "type": "container.v1.cluster",
        "properties": {
            "name": CLUSTER_NAME,
            "initialClusterVersion": INITIAL_CLUSTER_VERSION,
            "nodePools": [{
                "machineType": MACHINE_TYPE,
                "management": { "autoRepair": True },
                "initialNodeCount": INITIAL_NODE_COUNT,
                "config": {
                    "serviceAccount": SERVICE_ACCOUNT,
                    "oauthScopes": [
                        "https://www.googleapis.com/auth/compute",
                        "https://www.googleapis.com/auth/devstorage.read_only",
                        "https://www.googleapis.com/auth/logging.write",
                        "https://www.googleapis.com/auth/monitoring"
                    ]
                }
            }],
            "locations": [ ZONE ],
            "ipAllocationPolicy": { "useIpAliases": True },
            "loggingService": "logging.googleapis.com",
            "monitoringService": "monitoring.googleapis.com",
            "zone": context.properties["zone"],
        }
    }]
    outputs = []
    return { "resources": resources, "outputs": outputs }
```

When I try to create a deployment, I get the following error: 

```
Missing property in path $['resource']['properties']['cluster']
```

This leads me to believe that the examples are the source of truth and not the documentation. Can someone help me figure out what I'm doing wrong?

**Comment by ocsig** [comment]
Thank you for your feedback, our team hear you loud and clear. We are working together with the documentation team to improve the usability and remove the ambiguity around the types and their properties used in Deployment Manager.

Let me try to explain what is happening here:

- Some of the GCP APIs working really well, "out of the box" with the Deployment manager engine. For example: gcp-types/compute-v1:firewalls. This means the dicovery document of the API is used as it is, without any input mapping or other overwrites. This also means the API documentations is a good source.

- There are APIs which working a bit differently. For example one of the parameter is in the API path and not in the request body. In this case, input mapping may be needed. You can read more about input mapping in the [custom type provider](https://cloud.google.com/deployment-manager/docs/configuration/type-providers/advanced-configuration-options) section.

It is not always obvious what changes and why got applied and currently the best source is the 'examples/v2' and 'google/resource-snippets' folders. Soon there will be additional information about custom behaviour of the types.

Last but not least, please take a look at the [CloudFoundation Toolkit](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates) implementation, it may saves you a lots of time as well. ( Currently we are pushing major updates to the new repo.)
