### ISSUE TITLE
Shared VPC: Only share specific subnetwork

### ISSUE THREAD

**Issue by bbzg** [GoogleCloudPlatform/deploymentmanager-samples#465]
I would like to know how to create a Shared VPC, but only sharing specific subnetworks to specific projects, instead of all subnetworks to all projects.

I can't figure out how to do it using Deployment Manager, and it seems very haphazard to string together a bunch of gcloud commands as described in the steps of [Provisioning Shared VPC/Service Project Admins for some subnets](https://cloud.google.com/vpc/docs/provisioning-shared-vpc#networkuseratsubnet).

Thanks!

**Comment by ocsig** [comment]
The Cloud Foundation Toolkit - Project Factory template supports shared VPC ( host and guest) projects with the explicit list of shared subnets:
[https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates/project](current stable version)
[https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/cft-dm-dev/dm/templates/project](Latest dev version)

Attaching a project to a Shared VPC host project and to 1 subnet:
`
      sharedVPC: test-vpc-host-project
      sharedVPCSubnets:
        - subnetId: subnet-1
          region: us-east1
`

**Comment by bbzg** [comment]
@ocsig That's really awesome, but where can I find documentation on the gcp-types? Teach a man to fish, as they say...

**Comment by ocsig** [comment]
I am happy to say, the DM team is working on improving the gcp-types documentation, stay tuned. As a general rule of thumb, the gcp-types are 1:1 matching to the underlying API (including the version). There are exceptions, those are usually a workaround for an underlying incompatibility.

In your case, these are fairly complex behaviours, but we hear you. My team works on the Cloud Foundation Toolkit repo, which meant to give you ready to use templates ( net to catch your fish :D ) as well as demonstrate good practices and high quality solutions. We are happy to hear any feedback related to DM/types/CFT.

(FYI: the new CFT repo is getting a large code upgrade soon ( see dev branch), which will include versioning, type upgrades, new features.)

My DM "How to find my info" checklist:

- [CFT Repo templates](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates)
- [DM Samples examples/v2](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2)
- [DM resource snippets for GCP-types](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/google/resource-snippets
- API documentation page
- DM samples repo issues > feel free to ask

**Comment by bbzg** [comment]
👏 thank you!
