### ISSUE TITLE
Unable to Find execute this yaml, error says 'Kind' is missing

### ISSUE THREAD

**Issue by pankajjeet001** [GoogleCloudPlatform/deploymentmanager-samples#472]
Hi during deployment of this yaml code, it says following error all of sudden though it used to work previously.

error: unable to decode "deptest.yaml": Object 'Kind' is missing in '{"resources":[{"name":"quickstart-deployment-vm","properties":{"disks":[{"autoDelete":true,"boot"

Please suggest the corrective action, i need to take.
![image](https://user-images.githubusercontent.com/43492937/60235069-20a1d700-98c4-11e9-8c6d-7041dc2621c2.png)

**Comment by pankajjeet001** [comment]
This is resolved by myself. Actually, i was trying to deploy yaml using kubectl instead of using deployment-manager. I actually overlapped while working in GKE vs non GKE environment.  ;-)

**Comment by mountainsaxena** [comment]
Given that you are working across mixed environments you may want to look
at https://github.com/GoogleCloudPlatform/k8s-config-connector
