### ISSUE TITLE
Update GKE sample to use OpenAPI specs

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/deploymentmanager-samples#48]
The ```/swagger.json``` endpoint is the more recent OpenAPI spec endpoint as described [here](https://kubernetes.io/docs/concepts/overview/kubernetes-api/)

Suggest updating the [GKE samples](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/examples/v2/gke/jinja/cluster.jinja#L62
)  to utilize it instead of  1.2 ```/swaggerapi/```

**Comment by krwenholz** [comment]
Hi @salrashid123,

Thanks for the suggestion. We're currently in the process of overhauling those examples as we add better support for Kubernetes. That endpoint should be updated in the process (over the next few months).

Thanks again.

**Comment by salrashid123** [comment]
@krwenholz   This issue should be reopened until this is addressed.

DM has several issues with GKE's swagger specs (or rather, generic specs):

1. incorrectly parsing a `$ref` as you pointed out

```
$ gcloud deployment-manager deployments create gke --config cluster.yaml 
The fingerprint of the deployment is pWgz_bM2aCF4NsJTqvSARg==
Waiting for create [operation-1528649714266-56e4c7f346f91-9ecd4e46-612c3535]...failed.                                                                                                                            
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1528649714266-56e4c7f346f91-9ecd4e46-612c3535]: errors:
- code: RESOURCE_ERROR
  location: /deployments/gke/resources/gke-type-provider
  message: '{"ResourceType":"deploymentmanager.v2beta.typeProvider","ResourceErrorCode":"INVALID_FIELD_VALUE","ResourceErrorMessage":"location:
    $.definitions.io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps.properties\n\"Invalid
    reference format, expected a reference of type string but got [OBJECT].\""}'
```
  (i looked into that issue incase it was a GKE problem but its not:   https://github.com/kubernetes/kubernetes/issues/59513)


2. Circular references.   
   The specs include ciruclar references within them and DM can't process them currently.
I don't have the actual output from a GKE `swagger.json` file handy but the error looked something like this:

```
$ gcloud deployment-manager deployments create circular --config custom_type_provider.yaml
The fingerprint of the deployment is MZ_HhslHP8YwdmTC5T4Ahg==
Waiting for create [operation-1519656456377-5661e974352a8-03070ff3-8815fdf6]...failed.                                                                                                                            
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1519656456377-5661e974352a8-03070ff3-8815fdf6]: errors:
- code: RESOURCE_ERROR
  location: /deployments/circular/resources/tasks-type-provider
  message: '{"ResourceType":"deploymentmanager.v2beta.typeProvider","ResourceErrorCode":"INVALID_FIELD_VALUE","ResourceErrorMessage":"location:
    $.definitions.Product.properties.parent_product\n\"Cyclic reference definition
    found [#/definitions/Product].\""}'
```

**Comment by krwenholz** [comment]
Hi @GieForce and @salrashid123,

I moved on from Deployment Manager and Google earlier this year. I'm sorry you're still seeing this issue and another bug hasn't been opened for it. You could try hitting up the folks who have made recent commits to this repo, contacting GCP support, or opening a new bug.

Best,

Kyle

**Comment by salrashid123** [comment]
@aljim   Could you reopen this issue (i could open a new bug w/ same content but this one was closed prematurely).  It'd also be pretty useful to support the swagger endpoint since users can instrument CRDs that get setup as part of the cluster..

**Comment by csabakollar** [comment]
We are currently blocked by this issue, because we can't create CRDs with deployment manager.

**Comment by mans0954** [comment]
According to https://kubernetes.io/docs/concepts/overview/kubernetes-api/, `/swaggerapi`, and `/swagger.json` are both going away in favour of ` /openapi/v2` in Kubernetes 1.14. I'm hitting the same error as @salrashid123 trying to use ` /openapi/v2` against a `1.11.6-gke.2` master:
```
gcloud --project ol-stag deployment-manager deployments update test-type --template kubernetes/resource-templates/type-provider2.jinja --properties k8s_endpoint:**.**.**.**
The fingerprint of the deployment is r7vOYhgiaX-As3l75JTVfA==
Waiting for update [operation-1549381350298-5812775019327-badec3c1-ce58aeef]...failed.                                                                       
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1549381350298-5812775019327-badec3c1-ce58aeef]: errors:
- code: RESOURCE_ERROR
  location: /deployments/test-type/resources/type2
  message: '{"ResourceType":"deploymentmanager.v2beta.typeProvider","ResourceErrorCode":"INVALID_FIELD_VALUE","ResourceErrorMessage":"location:
    $.definitions.io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps.properties\n\"Invalid
    reference format, expected a reference of type string but got [OBJECT].\""}'
```

**Comment by salrashid123** [comment]
@mans0954 @GieForce @csabakollar  pls see PR https://github.com/GoogleCloudPlatform/deploymentmanager-samples/pull/384

There were some fixes last week in the DM backend which addressed those parsing errors.  The pr updates the dm samples for gke for openapi2 and at the sametime addresses what seems to me an inputMapping flaw that was there all this time.  Also upgrades the api version of deployment and provides a very basic CRD example.

**Comment by csabakollar** [comment]
@salrashid123 it worked for me, thank you! :)
