### ISSUE TITLE
How do you import files programmatically?

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/deploymentmanager-samples#500]
Im looking at the cloud functions example and this is not going to work for me: https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/examples/v2/cloud_functions/python/cloud_function.yaml#L4

I cant force user to have to manually define EVERY file their function needs like this with explicit imports. I also want to use deployment manager to deploy multiple functions in a single stack which exacerbates this problem

How do you dynamically/programmatically import files? So I can just say all files under this folder? Or programmatically import files inside of the cloud_function.py script?

**Comment by ocsig** [comment]
This is the feature you are looking for:
https://cloud.google.com/sdk/docs/release-notes#cloud_deployment_manager

Turn on the glob imports flag:
`gcloud config set deployment_manager/glob_imports True`

Then use glob style imports in your yaml or schema files:
```
imports:
- path: templates/simple_frontend.py
  name: simple_frontend.py

# Helper classes
- path: helper/*.py

# Configuration files
- path: configs/*.yaml
- path: configs/*/*.yaml
```

You can see it in action here:
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/community/hierarchical_configuration/Basic
and here:
https://cloud.google.com/deployment-manager/docs/at-scale

On an other note, please take a look at the [CFT Cloud Functions template.](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates/cloud_function)

**Comment by red8888** [comment]
@ocsig yup thats what i wanted thanks!
