### ISSUE TITLE
cloudkms update 

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#51]
Hi, 
if I try to update a cloudkms deployment (for example modifying accessControl.gcpIamPolicy.bindings) I've the following error:

```
- code: RESOURCE_ERROR
  location: /deployments/resources/resources/my-keyring
  message: '{"ResourceType":"gcp-types/cloudkms-v1:projects.locations.keyRings","ResourceErrorCode":"404","ResourceErrorMessage":{"statusMessage":"Not
    Found","requestPath":"https://cloudkms.googleapis.com/v1/projects/my-project/locations/global/keyRings/my-keyring","httpMethod":"POST"}}'
```

Do you know how to avoid this behaviour?
Thanks

**Comment by krwenholz** [comment]
Hi Davide,

Can you provide the deployment before and after the update please? 

Thanks.

**Comment by davidebelloni** [comment]
Hi,
after a deployment delete (ABANDON) and deployment create now I can update the KeyRing e Key resources.

I don't know which nook I've found!

Thanks

**Comment by krwenholz** [comment]
So it's working? Excellent! Let us know if you need anything else.
