### ISSUE TITLE
examples/v2/cloud_functions does not explain how the files under 'function' get deployed

### ISSUE THREAD

**Issue by ensonic** [GoogleCloudPlatform/deploymentmanager-samples#57]
In both the jinja2 and python folders the cloud-functions are referenced as `gs://cloud-function-sample/function.zip`. This sounds like one you need to zip whatever is in the functions dir (with or without the directory) and use gsutil to upload it.
It would be nice to change the example to have the cloud-bucket uploading step as part of the deployment manager script.

**Comment by krwenholz** [comment]
Hi Stefan,

DM doesn't execute as a script, so we actually don't have a method for creating zip files and uploading them to GCS. I've clarified this in our functions sample README. Let me know if that's not clear enough though and we can rehash it in this thread.

**Comment by aljim** [comment]
The function code now is deployed as part of the deployment

**Comment by ensonic** [comment]
Thanks a lot. This is helpful.
