### ISSUE TITLE
Cloud Deployment manager error

### ISSUE THREAD

**Issue by chinpark** [GoogleCloudPlatform/deploymentmanager-samples#621]
Problem:
Following the readme and instructions of
https://github.com/tieto-pc/gcp-intro-dm-demo produces an error where reference to non-existent config file

When I try to run the cloud deployment command it throws this error

chinmay.parkar$ gcloud deployment-manager deployments create cparkar-project-deployment --template deployment.py --project cparkar-project
The fingerprint of the deployment is b'gs2fUJthaczGrQLE2sa4Kw=='
Waiting for create [operation-1614195862251-5bc1a42f7a685-192adad5-4fccd052]...failed.                                                                              
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1614195862251-5bc1a42f7a685-192adad5-4fccd052]: errors:
- code: MANIFEST_EXPANSION_USER_ERROR
  location: /deployments/cparkar-project-deployment/manifests/manifest-1614195862293
  message: "Manifest expansion encountered the following errors: Error compiling Python\
    \ code: No module named 'common' Resource: deployment.py Resource: config"

common.py is in the same working directory as deployment.py

I have tried importing common.py using various method but I am getting the same error.

Please check and advice.

**Comment by chinpark** [comment]
Hey, Thanks for the reply! @ocsig 

I tried as you suggested but it does not work :(

chinmay.parkar$ gcloud deployment-manager deployments create cparkar-project-deployment --config deployment.py --project cparkar-project
ERROR: (gcloud.deployment-manager.deployments.create) Creating deployments from templates with the --config flag is not supported. Please use the --template flag.

Please suggest!

**Comment by ocsig** [comment]
Please use the config yaml as a starting point/parameter for DM, not the deployment.py:
`--config deployment.py` >> `--config deployment.yaml`

**Comment by chinpark** [comment]
Thank you so much!!! @ocsig 
The issue is fixed!
