### ISSUE TITLE
Broken link to community/cloud-foundation on front page

### ISSUE THREAD

**Issue by dweekly** [GoogleCloudPlatform/deploymentmanager-samples#672]
README.md links to https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/community/cloud-foundation (context: "A large portion of the templates is available under community/cloud-foundation") but this link is 404.

**Comment by ocsig** [comment]
Thank you for reporting this. The Cloud Foundation Toolkit moved away from this repo long time ago. I removed the reference from the readme.
