### ISSUE TITLE
Project creation sample missing

### ISSUE THREAD

**Issue by peon-pasado-zeitnot** [GoogleCloudPlatform/deploymentmanager-samples#675]
Hi,
I was following the tutorial at: https://cloud.google.com/blog/products/gcp/automating-project-creation-with-google-cloud-deployment-manager.

It says:
>The project creation samples are available in the Deployment Manager github repo under the project_creation directory. Or clone the whole DM github repo:
git clone
https://github.com/GoogleCloudPlatform/deploymentmanager-samples.git

>Then copy the templates under the examples/v2/project_creation directory.

>Follow the steps in the Readme in the project_creation directory. The readme includes detailed instructions, but there is one point to emphasize. You should create a new project using the Cloud Console that will be used as your “Project Creation” project. The service account under which Deployment Manager runs needs powerful IAM permissions to create projects and manage billing accounts, hence the recommendation to create this special project and use it only for creation of other projects.

Unfortunately relevant example linked in the tutorial (https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/project_creation) returns 404.

**Comment by tector** [comment]
still missing :-/

**Comment by shahid-khattak** [comment]
and still missing....
