### ISSUE TITLE
References at runtime

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#83]
Hi, 
is it possible to use reference object informations in python template at runtime? 
For example cycle on the returned bindigs of the “cloudresourcemanager.projects.getIamPolicy” resource and create a dictionary, dependent on these values, for a “cloudresourcemanager.projects.setIamPolicy” resource?

Thanks

**Comment by davidebelloni** [comment]
Hi,
another use case is cycle on a "gcp-types/compute-v1:compute.regionInstanceGroupManagers.listManagedInstances" resource to insert a route for each ManagedInstances.

Do you have suggestions?

Thanks

**Comment by krwenholz** [comment]
Hi Davide,

Sorry, but we don't support usage of template references in that way. You would need to utilize a Cloud Function or Cloud Container Builder script to make this work. There are some plans to eventually support this in templates, but those are a ways out.

Sorry for the tardy response. It looks like something went wrong with our normal issue curation script.
