### ISSUE TITLE
Enable service APIs in template

### ISSUE THREAD

**Issue by dtretyakov** [GoogleCloudPlatform/deploymentmanager-samples#96]
Is it possible to enable required service APIs during the deployment the same way as `gcloud services enable <xxx>` does?

**Comment by dtretyakov** [comment]
I have made service enabling by leveraging undocumented `deploymentmanager.v2.virtual.enableService` resource type:
https://github.com/dtretyakov/teamcity-google-template/blob/master/enable-services.jinja

It would be great to add documentation about it.

**Comment by shuainie-google** [comment]
Hi @dtretyakov, we also have example template [here](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/2531e81d112b3c8d19ade750decfcf6a1c410843/examples/v2/project_creation/apis.py) to show how to use "deploymentmanager.v2.virtual.enableService". I will update our internal bug to make sure this is covered by our documentation.
